syntax = "proto3";

package auth;

option go_package = "gen/go/sso";

service Auth {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc IsAdmin (AdminRequest) returns (AdminResponse);
}

message RegisterRequest {
    string email = 1;
    string password = 2;
}

message RegisterResponse {
    string user_id = 1;
}

message LoginRequest {
    string email = 1;
    string password = 2;
    int32 app_id = 3;
}

message LoginResponse {
    string token = 1;
}

message AdminRequest {
    string user_id = 1;
}

message AdminResponse {
    bool is_admin = 1;
}