syntax = "proto3";

option go_package = "internal/gen/user;userpb";

package user;

service UserService {
    rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
    rpc LoginUser (LoginUserRequest) returns (LoginUserResponse);
    rpc GetUserById (GetUserByIdRequest) returns (GetUserByIdResponse);
    rpc GetUserByEmail (GetUserByEmailRequest) returns (GetUserByEmailResponse);
    rpc GetAccountById (GetAccountByIdRequest) returns (GetAccountByIdResponse);
    rpc DepositBalance (DepositBalanceRequest) returns (DepositBalanceResponse);
    rpc WithdrawBalance (WithdrawBalanceRequest) returns (WithdrawBalanceResponse);
    rpc CreateTransaction (CreateTransactionRequest) returns (CreateTransactionResponse);
}

message CreateUserRequest {
    string name = 1;
    string email = 2;
    string password = 3;
}

message CreateUserResponse {
    string id = 1;
    string name = 2;
    string email = 3;
    string secret_key = 4;
}

message LoginUserRequest {
    string email = 1;
    string password = 2;
}

message LoginUserResponse {
    string id = 1;
    bool success = 2;
    string message = 3;
}

message GetUserByIdRequest {
    string id = 1;
}

message GetUserByIdResponse {
    string id = 1;
    string name = 2;
    string email = 3;
}

message GetUserByEmailRequest {
    string email = 1;
}

message GetUserByEmailResponse {
    string id = 1;
    string name = 2;
    string email = 3;
}

message GetAccountByIdRequest {
    string id = 1;
}

message GetAccountByIdResponse {
    string accountId = 1;
    string id = 2;
    string name = 3;
    string email = 4;
    double balance = 5;
    string currency = 6;
}

message DepositBalanceRequest {
    string id = 1;
    double moneyCount = 2;
}

message DepositBalanceResponse {
    bool success = 1;
}

message WithdrawBalanceRequest {
    string id = 1;
    double moneyCount = 2;
}

message WithdrawBalanceResponse {
    bool success = 1;
}

message CreateTransactionRequest {
    string fromAccountId = 1;
    string toAccountId = 2;
    string transactionType = 3;
    double amount = 4;
    string description = 5;
}

message CreateTransactionResponse {
    string id = 1;
    string status = 2;
}
